name: Prepare Test Data

on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --with docs

      - name: Prepare test data
        run: |
          poetry run python -c "import tests.helpers.test_UK_USA_dataset_helpers as t; t.download_data_zip(); t.extract_data_zip();"

      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: tests/data/test3/
          key: test-data-v1
